Module1 task3
htmlacademy-nodejs/1419647-buy-and-sell-3 pull request #3
Opened 2020-03-28 00:12 UTC by margareti

2020-03-28 21:11 UTC, cmpxchg16b requested changes

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/generateCount.js
> +const titles = [
лучше вынести данные в отдельный файл

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/generateCount.js
> +  for (let i = limit; i > 0; i--) {
лучше разделить логику получения массива уникальных рандомных индексов и генерации дескрипшена:
1. do { ... } while(history.length <= limit)
2. const result = history.map(index => arr[index])
в этом случае упроститься код и будет приятнее читать

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/generateCount.js
> +const generateCount = (count = 1) => {
название ни о чем не говорит

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/generateCount.js
> +      sum: utils.getRandomArbitrary(1000, 100000),
магические числа, лучше использовать константы с говорящими именами

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/generateCount.js
> +const maxLimit = 1000;
константа, должна иметь специфическое имя:
MAX_LIMIT
и лучше все константы вынести в отдельный файл

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/generateCount.js
> +  fs.writeFile(`mock.json`, JSON.stringify(offers, null, 4), function () {
тут не нужно асинхронной обработки, лучше использовать sync версию функции: fs.writeFileSync

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/showHelp.js
> +  printInfo: () => console.log(`
лучше вынести из тела экспорта функцию

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/showVersion.js
> +  getVersion: () => console.log(version)
лучше вынести из тела экспорта функцию

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/service.js
> +const [...restOfArgs] = process.argv.slice(2);
зачем здесь деструктор? ты уже отфильтровала ненужные элементы

2020-03-28 21:11 UTC, cmpxchg16b commented on src/service/service.js
> +const customCommands = [{
лучше вынести всю работу с консолью в отдельный файл

2020-03-30 09:10 UTC, margareti commented
Спасибо тебе за ревю, сейчас забацаю в оба проекта!

2020-04-01 17:30 UTC, cmpxchg16b requested changes

2020-04-01 17:30 UTC, cmpxchg16b commented on src/service/generateMocks.js
> +  fs.writeFileSync(`mock.json`, JSON.stringify(offers, null, 4), () => 1);
обработку ошибок потеряла
метод выбросит исключение при ошибке

2020-04-01 17:30 UTC, cmpxchg16b commented on src/service/generateMocks.js
> +const getNonRepeatingIndex = (sourceArray, historyArray) => {
можно уже из этого метода возвращать последовательность уникальную

2020-04-01 17:30 UTC, cmpxchg16b commented on src/service/generateMocks.js
> +  for (let i = limit; i > 0; i--) {
если предыдущая функция возратит массив, можно .map сделать по ней и вернуть массив строк сразу

2020-04-02 18:02 UTC, cmpxchg16b requested changes

2020-04-02 18:02 UTC, cmpxchg16b commented on src/service/generateMocks.js
> +  fs.writeFileSync(`mock.json`, JSON.stringify(offers, null, 4), function() {
так, видно мы не допоняли друг друга.
1) writeFileSync имеют следующую сигнатуру
fs.writeFileSync(file, data[, options])
как видишь никакого коллбэка третьим параметром

2) в случае ошибки эта функция выбросит исключение, которое нужно поймать в try/catch

3) если исключения не было выброшено, вернуть 0. Если же было исключение - вернуть 1

2020-04-02 18:02 UTC, cmpxchg16b commented on src/service/generateMocks.js
> +  const indexes = [];
смотри, я хотел избавиться от вложенных циклов здесь
ты можешь использовать внешний цикл и внутри него добавлять индекс в массив, только если его нет уже

2020-04-02 18:02 UTC, cmpxchg16b commented on src/service/generateMocks.js
> +  const randomIndexes = getNonRepeatingIndexesArray(limit, arr.length);
NonRepeating === Unique
а еще так можно
return getNonRepeatingIndexesArray(limit, arr.length)
 .map(i => arr[i])

2020-04-12 17:15 UTC, cmpxchg16b approved these changes

2020-04-12 17:15 UTC, merged